# Site settings
title: "UIUX Conf China"
baseurl: ""
url: "http://2016.uiuxconf.com"
exclude: ['README.md', 'package.json', 'bower.json', 'Gemfile', 'gulpfile.js', 'node_modules', 'dist/scss', 'dist/js']
languages:          ['en', 'cn']
language_default:   'en'



collections:
  speakers:
    output: false
  sponsors:
    output: false
  medias:
    output: false


# Plugins
gems:
- jekyll-redirect-from
- jekyll-paginate
- jekyll-multiple-languages