# Site settings
title: "UIUX Conf China"
baseurl: ""
url: "http://test.uiuxconf.com"
exclude: ['README.md', 'package.json', 'bower.json', 'Gemfile', 'gulpfile.js', 'node_modules', 'bower_components', 'assets/scss']
languages:          ['en', 'cn']
language_default:   'en'
# Plugins
gems:
- jekyll-redirect-from
- jekyll-paginate
- jekyll-multiple-languages